version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: tap
    versions:
    - 14.11.0
    - 15.0.0
    - 15.0.1
    - 15.0.2
    - 15.0.3
    - 15.0.4
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: marked
    versions:
    - 1.2.8
    - 1.2.9
    - 2.0.0
    - 2.0.1
  - dependency-name: "@snyk/nodejs-runtime-agent"
    versions:
    - 1.47.2
  - dependency-name: file-type
    versions:
    - 16.2.0
  - dependency-name: ejs
    versions:
    - 3.1.5
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
